services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  shawnhu444/dsci522-individual-assignment3:a0fa9c8
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
