services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  shawnhu444/Breadcrumbsdsci522_Individual_assignment3
:61da14e
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
